@url=http://localhost:3000
@token=place_token_here
### --- ENDPOINTS FOR DEVELOPERS RESOURCES ---
GET {{url}}/developers
Authorization: Bearer {{token}}

###
GET {{url}}/developers/1
Authorization: Bearer {{token}}

###
POST {{url}}/developers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "CD Projekt Red 2"
}

###
PATCH {{url}}/developers/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "CD Projekt Red Original"
}

###
DELETE {{url}}/developers/1
Authorization: Bearer {{token}}


### --- ENDPOINTS FOR GAMES RESOURCES ---
GET {{url}}/games
Authorization: Bearer {{token}}

###
GET {{url}}/games/1
Authorization: Bearer {{token}}

###
POST {{url}}/games
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "The Witcher 3",
  "releaseDate": "2015-05-19",
  "developerId": 2
}

###
PATCH {{url}}/games/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "The Witcher 2: Update"
}

###
DELETE {{url}}/games/2
Authorization: Bearer {{token}}

### --- ENDPOINTS FOR USERS RESOURCES ---
GET {{url}}/users
Authorization: Bearer {{token}}

###
GET {{url}}/users/1
Authorization: Bearer {{token}}

###
POST {{url}}/users
Content-Type: application/json

{
  "username": "Test",
  "email": "test@example.com",
  "password": "123456789"
}

###
PATCH {{url}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role": "admin"
}

###
DELETE {{url}}/users/1
Authorization: Bearer {{token}}

### --- ENDPOINTS FOR TESTING AUTH ---
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456789"
}

###
GET {{url}}/auth/profile
Authorization: Bearer {{token}}
