services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pswd
            POSTGRES_DB: gamesDb
        ports: [5433:5432]
